---

version: 2

jobs:
  build:
    docker:
      - image: bdockerimg/bmakelib:0.7.0--opensuse-tumbleweed
        environment:
          LANG: en_US.UTF-8
          JVM_OPTS: -Xmx1024m

    working_directory: ~/bpgnlib

    steps:
      - run:
          name: Install the runtime
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install java-21-openjdk-devel
            && { source /etc/profile || true; }

      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "bpgnlib/build.gradle" }}
            - dependencies-

      - run:
          name: Fetch the dependencies and compile
          command: >-
            make compile

      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "bpgnlib/build.gradle" }}

      - run:
          name: Run the tests
          command: >-
            make test

      - store_artifacts:
          path: lib/build/reports
          destination: test-reports

      - store_test_results:
          path: lib/build/test-results
